//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsNotepad.Recource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsNotepad.Recource.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date added to the database.
        /// </summary>
        internal static string by_date_added_to_the_database {
            get {
                return ResourceManager.GetString("by_date_added_to_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the name.
        /// </summary>
        internal static string by_the_name {
            get {
                return ResourceManager.GetString("by_the_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the Nick Name.
        /// </summary>
        internal static string by_the_nick_name {
            get {
                return ResourceManager.GetString("by_the_nick_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language:.
        /// </summary>
        internal static string change_the_language {
            get {
                return ResourceManager.GetString("change_the_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password .
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coordinates.
        /// </summary>
        internal static string coordinates {
            get {
                return ResourceManager.GetString("coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dark theme .
        /// </summary>
        internal static string enable_dark_theme {
            get {
                return ResourceManager.GetString("enable_dark_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label and Latitude and Longitude fields must be filled!.
        /// </summary>
        internal static string information_is_missing_in_the_fields_label_and_latitude_and_longitude {
            get {
                return ResourceManager.GetString("information_is_missing_in_the_fields_label_and_latitude_and_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data entered.
        /// </summary>
        internal static string invalid_data_entered {
            get {
                return ResourceManager.GetString("invalid_data_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password!.
        /// </summary>
        internal static string invalid_email_or_password {
            get {
                return ResourceManager.GetString("invalid_email_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string label_of_pin {
            get {
                return ResourceManager.GetString("label_of_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pins added.
        /// </summary>
        internal static string no_pins_added {
            get {
                return ResourceManager.GetString("no_pins_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and login do not exist in the database!.
        /// </summary>
        internal static string password_or_user_name_does_not_exist {
            get {
                return ResourceManager.GetString("password_or_user_name_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick at gallery.
        /// </summary>
        internal static string pick_at_gallery {
            get {
                return ResourceManager.GetString("pick_at_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a photo.
        /// </summary>
        internal static string please_pick_a_photo {
            get {
                return ResourceManager.GetString("please_pick_a_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 and no more than 16 characters and contain at least one uppercase letter, one lowercase letter and one number.
        /// </summary>
        internal static string requirements_for_password_and_confirm_password {
            get {
                return ResourceManager.GetString("requirements_for_password_and_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements for creating an email address are not met.
        /// </summary>
        internal static string requirements_to_email {
            get {
                return ResourceManager.GetString("requirements_to_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 and no more than 16 characters and contain at least one uppercase letter, one lowercase letter and one number!.
        /// </summary>
        internal static string requirements_to_password {
            get {
                return ResourceManager.GetString("requirements_to_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sorting option:.
        /// </summary>
        internal static string select_sorting_option {
            get {
                return ResourceManager.GetString("select_sorting_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo with camera.
        /// </summary>
        internal static string take_photo_with_camera {
            get {
                return ResourceManager.GetString("take_photo_with_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already taken!.
        /// </summary>
        internal static string this_login_is_already_taken {
            get {
                return ResourceManager.GetString("this_login_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pin.
        /// </summary>
        internal static string title_add_pin {
            get {
                return ResourceManager.GetString("title_add_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        internal static string title_main_list {
            get {
                return ResourceManager.GetString("title_main_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        internal static string title_sign_in {
            get {
                return ResourceManager.GetString("title_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string title_sign_up {
            get {
                return ResourceManager.GetString("title_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You really want to delete this profile?.
        /// </summary>
        internal static string you_really_want_to_delete_this_profile {
            get {
                return ResourceManager.GetString("you_really_want_to_delete_this_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        internal static string your_email {
            get {
                return ResourceManager.GetString("your_email", resourceCulture);
            }
        }
    }
}
